export const RANDOM_PICK_HOP_COUNT = 18;
export const RANDOM_PICK_HOP_INTERVAL_MS = 90;
export const RANDOM_PICK_SETTLE_DELAY_MS = 80;
export const RANDOM_PICK_ANIMATION_DURATION_MS =
  RANDOM_PICK_HOP_COUNT * RANDOM_PICK_HOP_INTERVAL_MS +
  RANDOM_PICK_SETTLE_DELAY_MS;
