packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  micromark: false
  node-pty: false
  prisma: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - 'prisma'
  - '@scarf/scarf'
  - 'bcryptjs'
  - 'micromark'
  - 'esbuild'
