import {
  RelationStatus,
  SeatCellType,
  StudentStatus,
  TeacherRole,
  UserStatus,
} from '@prisma/client';
import type { PrismaClient } from '@prisma/client';
import { prisma } from '../../plugins/prisma';
import { ClassEventType } from '../realtime/realtime.types';
import { realtimeService } from '../realtime/realtime.service';
import { rotateOccupiedSeatsRight, type RotationSeat } from './seat-rotation';

export const TAIPEI_TIME_ZONE = 'Asia/Taipei';
const TAIPEI_OFFSET_MS = 8 * 60 * 60 * 1000;

export type WeeklyRotationSkipReason =
  | 'ALREADY_ROTATED'
  | 'NO_LAYOUT'
  | 'LAYOUT_CREATED_AFTER_SCHEDULE'
  | 'NO_ACTIVE_HEAD_TEACHER'
  | 'NO_ROTATABLE_ROWS'
  | 'INVALID_STUDENT_LAYOUT'
  | 'CONCURRENT_LAYOUT_CHANGE';

export interface ClassWeeklyRotationResult {
  classId: string;
  status: 'ROTATED' | 'SKIPPED' | 'FAILED';
  reason?: WeeklyRotationSkipReason;
  version?: number;
  error?: string;
}

export interface WeeklyRotationRunResult {
  weekKey: string;
  scheduledAt: string;
  due: boolean;
  classes: ClassWeeklyRotationResult[];
}

export interface WeeklySeatingRotationTask {
  cronExpression: string;
  timezone: typeof TAIPEI_TIME_ZONE;
  run: (now?: Date) => Promise<WeeklyRotationRunResult>;
}

interface TaipeiWeekBoundary {
  weekKey: string;
  scheduledAt: Date;
}

class ConcurrentLayoutChangeError extends Error {
  constructor() {
    super('The current seat layout changed while weekly rotation was preparing a snapshot');
  }
}

function getTaipeiWeekBoundary(now: Date): TaipeiWeekBoundary {
  const taipeiNow = new Date(now.getTime() + TAIPEI_OFFSET_MS);
  const weekday = taipeiNow.getUTCDay();
  const daysSinceMonday = (weekday + 6) % 7;
  const monday = new Date(taipeiNow);
  monday.setUTCDate(monday.getUTCDate() - daysSinceMonday);
  const weekKey = monday.toISOString().slice(0, 10);
  const scheduledAt = new Date(Date.parse(`${weekKey}T00:05:00+08:00`));
  return { weekKey, scheduledAt };
}

function rotationMarkerWhere(classId: string, weekKey: string): unknown {
  // The database worker adds rotationWeekKey to the generated Prisma client.
  // Keep this narrow cast until that client is regenerated by the integrator.
  return { classId, rotationWeekKey: weekKey };
}

function rotationLayoutData(
  classId: string,
  version: number,
  sourceVersionId: string,
  createdBy: string,
  weekKey: string,
): unknown {
  // See rotationMarkerWhere: this is the one field supplied by the database
  // worker and is intentionally isolated from the rest of the service.
  return { classId, version, sourceVersionId, createdBy, rotationWeekKey: weekKey };
}

function isUniqueConstraintError(error: unknown): boolean {
  return (
    typeof error === 'object' &&
    error !== null &&
    'code' in error &&
    (error as { code?: unknown }).code === 'P2002'
  );
}

function asRotationSeat(seat: {
  rowIndex: number;
  colIndex: number;
  studentId: string | null;
  cellType: SeatCellType;
}): RotationSeat {
  return {
    rowIndex: seat.rowIndex,
    colIndex: seat.colIndex,
    studentId: seat.studentId,
    cellType: seat.cellType,
  };
}

export class WeeklySeatingRotationService {
  constructor(
    private readonly db: PrismaClient = prisma,
    private readonly events: typeof realtimeService = realtimeService,
  ) {}

  async run(now = new Date()): Promise<WeeklyRotationRunResult> {
    const { weekKey, scheduledAt } = getTaipeiWeekBoundary(now);
    if (now < scheduledAt) {
      return {
        weekKey,
        scheduledAt: scheduledAt.toISOString(),
        due: false,
        classes: [],
      };
    }

    const classrooms = await this.db.classroom.findMany({
      where: { status: 'ACTIVE' },
      select: { id: true },
      orderBy: { id: 'asc' },
    });
    const classes: ClassWeeklyRotationResult[] = [];

    for (const classroom of classrooms) {
      try {
        classes.push(await this.rotateClass(classroom.id, weekKey, scheduledAt));
      } catch (error) {
        classes.push({
          classId: classroom.id,
          status: 'FAILED',
          error: error instanceof Error ? error.message : '未知错误',
        });
      }
    }

    return {
      weekKey,
      scheduledAt: scheduledAt.toISOString(),
      due: true,
      classes,
    };
  }

  private async rotateClass(
    classId: string,
    weekKey: string,
    scheduledAt: Date,
  ): Promise<ClassWeeklyRotationResult> {
    try {
      const result = await this.db.$transaction(async (tx) => {
        const existingRotation = await tx.seatLayoutVersion.findFirst({
          where: rotationMarkerWhere(classId, weekKey) as never,
          select: { id: true, version: true },
        });
        if (existingRotation) {
          return {
            classId,
            status: 'SKIPPED' as const,
            reason: 'ALREADY_ROTATED' as const,
          };
        }

        const classroom = await tx.classroom.findUnique({
          where: { id: classId },
          select: { currentLayoutVersionId: true },
        });
        if (!classroom?.currentLayoutVersionId) {
          return { classId, status: 'SKIPPED' as const, reason: 'NO_LAYOUT' as const };
        }

        const headTeacher = await tx.classTeacher.findFirst({
          where: {
            classId,
            role: TeacherRole.HEAD_TEACHER,
            status: RelationStatus.ACTIVE,
            teacher: { status: UserStatus.ACTIVE },
          },
          select: { teacherId: true },
        });
        if (!headTeacher) {
          return {
            classId,
            status: 'SKIPPED' as const,
            reason: 'NO_ACTIVE_HEAD_TEACHER' as const,
          };
        }

        const current = await tx.seatLayoutVersion.findUnique({
          where: { id: classroom.currentLayoutVersionId },
          select: {
            id: true,
            createdAt: true,
            seats: {
              orderBy: [{ rowIndex: 'asc' }, { colIndex: 'asc' }],
              select: { rowIndex: true, colIndex: true, studentId: true, cellType: true },
            },
          },
        });
        if (!current) {
          return { classId, status: 'SKIPPED' as const, reason: 'NO_LAYOUT' as const };
        }
        if (current.createdAt > scheduledAt) {
          return {
            classId,
            status: 'SKIPPED' as const,
            reason: 'LAYOUT_CREATED_AFTER_SCHEDULE' as const,
          };
        }

        const studentIds = current.seats
          .map((seat) => seat.studentId)
          .filter((studentId): studentId is string => Boolean(studentId));
        const distinctStudentIds = new Set(studentIds);
        if (distinctStudentIds.size !== studentIds.length) {
          return {
            classId,
            status: 'SKIPPED' as const,
            reason: 'INVALID_STUDENT_LAYOUT' as const,
          };
        }
        if (studentIds.length > 0) {
          const activeStudents = await tx.student.findMany({
            where: { classId, id: { in: studentIds } },
            select: { id: true, status: true, deletedAt: true },
          });
          if (
            activeStudents.length !== distinctStudentIds.size ||
            activeStudents.some(
              (student) => student.status !== StudentStatus.ACTIVE || student.deletedAt !== null,
            )
          ) {
            return {
              classId,
              status: 'SKIPPED' as const,
              reason: 'INVALID_STUDENT_LAYOUT' as const,
            };
          }
        }

        const rotated = rotateOccupiedSeatsRight(current.seats.map(asRotationSeat));
        if (rotated.rotatedRows.length === 0) {
          return {
            classId,
            status: 'SKIPPED' as const,
            reason: 'NO_ROTATABLE_ROWS' as const,
          };
        }

        const latest = await tx.seatLayoutVersion.findFirst({
          where: { classId },
          orderBy: { version: 'desc' },
          select: { version: true },
        });
        const nextVersion = (latest?.version ?? 0) + 1;
        const layout = await tx.seatLayoutVersion.create({
          data: rotationLayoutData(
            classId,
            nextVersion,
            current.id,
            headTeacher.teacherId,
            weekKey,
          ) as never,
          select: { id: true, version: true },
        });

        await tx.seat.createMany({
          data: rotated.seats.map((seat) => ({
            layoutVersionId: layout.id,
            rowIndex: seat.rowIndex,
            colIndex: seat.colIndex,
            studentId: seat.studentId,
            cellType: seat.cellType,
          })),
        });

        const switched = await tx.classroom.updateMany({
          where: { id: classId, currentLayoutVersionId: current.id },
          data: { currentLayoutVersionId: layout.id },
        });
        if (switched.count !== 1) {
          throw new ConcurrentLayoutChangeError();
        }

        return {
          classId,
          status: 'ROTATED' as const,
          version: layout.version,
          sourceVersionId: current.id,
          rotatedRows: rotated.rotatedRows,
        };
      });

      if (result.status === 'ROTATED') {
        this.events.publishClassEvent(classId, {
          id: `${classId}-layout-rotation-${weekKey}`,
          type: ClassEventType.SEAT_LAYOUT_CHANGED,
          classId,
          occurredAt: new Date().toISOString(),
          payload: {
            version: result.version,
            sourceVersionId: result.sourceVersionId,
            rotationWeekKey: weekKey,
            source: 'WEEKLY_ROTATION',
            rotatedRows: result.rotatedRows,
          },
        });
      }

      return result;
    } catch (error) {
      if (error instanceof ConcurrentLayoutChangeError) {
        return { classId, status: 'SKIPPED', reason: 'CONCURRENT_LAYOUT_CHANGE' };
      }
      if (isUniqueConstraintError(error)) {
        const marker = await this.db.seatLayoutVersion.findFirst({
          where: rotationMarkerWhere(classId, weekKey) as never,
          select: { id: true },
        });
        if (marker) {
          return { classId, status: 'SKIPPED', reason: 'ALREADY_ROTATED' };
        }
        return { classId, status: 'SKIPPED', reason: 'CONCURRENT_LAYOUT_CHANGE' };
      }
      throw error;
    }
  }
}

export const weeklySeatingRotationService = new WeeklySeatingRotationService();

/**
 * Build the scheduler-owned task without coupling this module to a cron
 * package. The integrator supplies this task to the configured scheduler and
 * uses the returned timezone alongside the cron expression.
 */
export function createWeeklySeatingRotationTask(
  cronExpression: string,
  service: WeeklySeatingRotationService = weeklySeatingRotationService,
): WeeklySeatingRotationTask {
  if (!cronExpression.trim()) {
    throw new Error('SEAT_ROTATION_CRON must not be empty');
  }
  return {
    cronExpression,
    timezone: TAIPEI_TIME_ZONE,
    run: (now?: Date) => service.run(now),
  };
}
